### ISSUE TITLE
No curves, only straight path

### ISSUE THREAD

**Issue by abylikhsanov** [ros-planning/navigation_experimental#29]
Hi, I have a robot which can only travel in straight lines as it cannot do the rotation and linear at the same time.
How can I change the parameters so the path could give either linear x,y or angular commands? So before changing the direction, robot will stop and then execute the rotation and then stops again and perform linear

**Comment by mintar** [comment]
I assume you want to use `sbpl_lattice_planner` to do this. This is a good idea, since `sbpl_lattice_planner` can deal exactly with the kinds of kinematic constraints that you are describing.

Essentially, you have to generate a `*.mprim` file that describes your kinematics. You can use the Matlab files from the [sbpl](https://github.com/sbpl/sbpl) library to do that. Here is how:

```bash
$ git clone https://github.com/sbpl/sbpl.git
$ cd sbpl/matlab/mprim 
$ sudo apt install octave
$ octave-cli --persist genmprim.m
octave:1> genmprim('myrobot.mprim')
```

Now focus the terminal again and press "Enter" a couple of times until the script is done.

In order to generate the constraints that you want, you'll have to modify the `genmprim.m` file (or one of the other `genmprim*.m` files). For example, you should comment out all code that generates the curving motions, and you should probably comment the "turninplace" motions back in.

Once you have your `*.mprim` file, you can specify it via the `primitive_filename` parameter of `sbpl_lattice_planner`, like this: https://github.com/ros-planning/navigation_experimental/blob/4e4697337d02d12fd0756f273b45f7afbf8322b6/sbpl_lattice_planner/launch/move_base/move_base_sbpl.xml#L9

Also see:

* http://sbpl.net/node/52
* http://sbpl.net/node/45
* http://wiki.ros.org/sbpl
